# Stage 1: Dependencies
FROM node:20.15.1-alpine3.20 AS dependencies
# Set working directory
WORKDIR /app
# Copy application code
ADD . /app
# Install build dependencies
RUN apk add --no-cache python3 make g++
# Install app dependencies
RUN npm ci


# Stage 2: Build
FROM dependencies AS build
# Build the application (assuming there's a build step in your package.json scripts)
RUN npm run build


# Stage 3: Production
FROM node:20.15.1-alpine3.20 AS production
# Set working directory
WORKDIR /app
# Copy the built application and necessary files from the build stage
COPY --from=build /app/package.json /app/package-lock.json ./
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
# Copy any additional required files
COPY --from=build /app/setup.sh ./
# Make the setup script executable
RUN chmod +x ./setup.sh
# Expose the application port
EXPOSE 3000
# Define the command to run the application
CMD ["node", "dist/index.js"]