version: '3.9'

services:
  main:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - microservices
    # command: npm run start:prod main
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - microservices

networks:
  microservices:
